keyboard:
  matrix_positions:
    # Left Hand
    # Pinky (columns 1-3)
    - [[1,0], [0,1],  [2,1],  [1,2],    # Left pinky (north, west, east, south)
    # Ring (columns 4-6)
      [4,0],  [3,1],  [5,1],   [4,2],    # Left ring
    # Middle (columns 7-9)
      [7,0],  [6,1],  [8,1],   [7,2],    # Left middle
    # Index (columns 10-12)
      [10,0], [9,1], [11,1], [10,2],   # Left index
    # Right Hand
    # Index (columns 13-15)
      [13,0], [12,1],  [14,1], [13,2],   # Right index
    # Middle (columns 16-18)
      [16,0], [15,1],  [17,1], [16,2],   # Right middle
    # Ring (columns 19-21)
      [19,0], [18,1],  [20,1], [19,2],   # Right ring
    # Pinky (columns 22-24)
      [22,0], [21,1],  [23,1], [22,2]]   # Right pinky

    # Thumb clusters (sequential numbering)
    - [[10,3],  [9,4],  [11,4], [10,5],            # Left thumb cluster
      [13,3], [12,4],  [14,4], [13,5]]           # Right thumb cluster
    - [[10,6],  [9,7],  [11,7], [10,8],            # Left thumb cluster 2
      [13,6], [12,7],  [14,7], [13,8]]           # Right thumb cluster 2

  positions:
    # Used to determine if directional switch is on the same row
    # Left Hand
    # Pinky (columns 1-3)
    - [[1,0], [2,0],  [3,0],  [4,0],    # Left pinky (north, west, east, south)
    # Ring (columns 4-6)
      [5,0],  [6,0],  [7,0],   [8,0],    # Left ring
    # Middle (columns 7-9)
      [9,0],  [10,0],  [11,0],  [12,0],    # Left middle
    # Index (columns 10-12)
      [13,0], [14,0], [15,0], [16,0],   # Left index
    # Right Hand
    # Index (columns 13-15)
      [17,0], [18,0],  [19,0], [20,0],   # Right index
    # Middle (columns 16-18)
      [21,0], [22,0],  [23,0], [24,0],   # Right middle
    # Ring (columns 19-21)
      [25,0], [26,0],  [27,0], [28,0],   # Right ring
    # Pinky (columns 22-24)
      [29,0], [30,0],  [31,0], [32,0]]   # Right pinky

    # Thumb clusters (sequential numbering)
    - [[1,1],  [2,1],  [3,1], [4,1],            # Left thumb cluster
      [5,1], [6,1],  [7,1], [8,1]]           # Right thumb cluster
    - [[1,2],  [2,2],  [3,2], [4,2],            # Left thumb cluster 2
      [5,2], [6,2],  [7,2], [8,2]]           # Right thumb cluster 2

  hands:
    # Main key rows (rows 1-3)
    - [Left, Left, Left, Left,      # Left pinky positions
       Left, Left, Left, Left,      # Left ring positions
       Left, Left, Left, Left,      # Left middle positions
       Left, Left, Left, Left,      # Left index positions
       Right, Right, Right, Right, # Right index positions
       Right, Right, Right, Right, # Right middle positions
       Right, Right, Right, Right, # Right ring positions
       Right, Right, Right, Right] # Right pinky positions
    
    # Thumb row (row 4)
    - [Left, Left, Left, Left,            # Left thumb cluster
       Right, Right, Right, Right]        # Right thumb cluster
    - [Left, Left, Left, Left,            # Left thumb cluster 2
       Right, Right, Right, Right]        # Right thumb cluster 2

  directions:
    # Main key rows (rows 1-3)
    - [North, West, East, South,      # Left pinky positions
       North, West, East, South,      # Left ring positions
       North, West, East, South,    # Left middle positions
       North, West, East, South,    # Left index positions
       North, West, East, South, # Right index positions
       North, West, East, South, # Right middle positions
       North, West, East, South, # Right ring positions
       North, West, East, South] # Right pinky positions
    
    # Thumb row (row 4)
    - [North, West, East, South,            # Left thumb cluster
       North, West, East, South]        # Right thumb cluster
    - [North, West, East, South,            # Left thumb cluster 2
       North, West, East, South]        # Right thumb cluster 2

  fingers:
    - [Pinky, Pinky, Pinky, Pinky,   # Left pinky positions
       Ring, Ring, Ring, Ring,         # Left ring positions
       Middle, Middle, Middle, Middle, # Left middle positions
       Index, Index, Index, Index,     # Left index positions
       Index, Index, Index, Index,     # Right index positions
       Middle, Middle, Middle, Middle, # Right middle positions
       Ring, Ring, Ring, Ring,         # Right ring positions
       Pinky, Pinky, Pinky, Pinky]   # Right pinky positions
    
    # Thumb row (row 4)
    - [Thumb, Thumb, Thumb, Thumb,           # Left thumb cluster
       Thumb, Thumb, Thumb, Thumb]           # Right thumb cluster
    - [Thumb, Thumb, Thumb, Thumb,           # Left thumb cluster 2
       Thumb, Thumb, Thumb, Thumb]           # Right thumb cluster 2

  key_costs:
      # N    W    E   S
      - [6,  10,   9,  5,     # Left pinky
        4,   8,   7,  3,     # Left ring
        2,   5,   4,  1,     # Left middle
        2,   5,   4,  1,     # Left index
        2,   4,   5,  1,     # Right index
        2,   4,   5,  1,     # Right middle
        4,   7,   8,  3,     # Right ring
        6,   9,   10,  5]     # Right pinky
      
      # Thumb row (row 4)
      - [5, 3, 4, 6,            # Left thumb cluster
        6, 3, 4, 5]            # Right thumb cluster
      - [6, 4, 5, 7,            # Left thumb cluster 2
        7, 4, 5, 6]            # Right thumb cluster 2

  unbalancing_positions:
    # Main key rows (rows 1-3)
    - [[0, 0], [0, 0], [0,0], [0, 0],     # Left pinky
      [0, 0], [0, 0],  [0, 0], [0, 0],     # Left ring
      [0, 0], [0, 0],  [0, 0], [0, 0],     # Left middle
      [0, 0], [0, 0],  [0, 0], [0, 0],     # Left index
      [0, 0], [0, 0],  [0, 0], [0, 0],     # Right index
      [0, 0], [0, 0],  [0, 0], [0, 0],     # Right middle
      [0, 0], [0, 0],  [0, 0], [0, 0],     # Right ring
      [0, 0], [0, 0],  [0, 0], [0, 0]]     # Right pinky
    
    # Thumb row (row 4)
    - [[0, 0], [0, 0], [0, 0], [0, 0],             # Left thumb cluster
      [0, 0], [0, 0], [0, 0], [0, 0]]             # Right thumb cluster
    - [[0, 0], [0, 0], [0, 0], [0, 0],             # Left thumb cluster 2
      [0, 0], [0, 0], [0, 0], [0, 0]]             # Right thumb cluster 2

  symmetries:
    # Main key rows (rows 1-3)
    - [1, 2, 3, 4,         # Left pinky
       5, 6, 7, 8,        # Left ring
       9, 10, 11, 12,    # Left middle
       13, 14, 15, 16,    # Left index
       16, 15, 14, 13,    # Right index (mirrored)
       12, 11, 10, 9,     # Right middle (mirrored)
       8, 7, 6, 5,         # Right ring (mirrored)
       4, 3, 2, 1]         # Right pinky (mirrored)
    
    # Thumb row (row 4)
    - [17, 18, 19, 20,        # Left thumb cluster
      20, 19, 18, 17]        # Right thumb cluster (mirrored)
    - [21, 22, 23, 24,        # Left thumb cluster
      24, 23, 22, 21]        # Right thumb cluster (mirrored)

  finger_resting_positions:
    Left:
      Pinky: [1,1]
      Ring: [4,1]
      Middle: [7,1]
      Index: [10,1]
      Thumb: [10,4]
    Right:
      Index: [13,1]
      Middle: [16,1]
      Ring: [19,1]
      Pinky: [22,1]
      Thumb: [13,4]


  plot_template: |2
              LEFT HAND                         RIGHT HAND

      Pinky   Ring    Middle  Index     Index   Middle  Ring    Pinky

        {{0}}       {{4}}       {{8}}       {{12}}         {{16}}       {{20}}       {{24}}       {{28}}
      {{1}}   {{2}}   {{5}}   {{6}}   {{9}}   {{10}}   {{13}}   {{14}}     {{17}}   {{18}}   {{21}}   {{22}}   {{25}}   {{26}}   {{29}}   {{30}}
        {{3}}       {{7}}       {{11}}       {{15}}         {{19}}       {{23}}       {{27}}       {{31}}

                              Thumb     Thumb

                                {{32}}         {{36}} 
                              {{33}}   {{34}}     {{37}}   {{38}}
                                {{35}}         {{39}}

                                {{40}}         {{44}} 
                              {{41}}   {{42}}     {{45}}   {{46}}
                                {{43}}         {{47}}


  plot_template_short:

base_layout:
  keys:
      # Main key rows (rows 1-3)
      - [["0"],["0"], ["0"], ["0"],     # Left pinky
        ["0"], [","], ["'"], ["u"],     # Left ring
        ["0"], ["."], ["i"], ["o"],     # Left middle
        ["0"], ["0"], ["r"], ["e"],     # Left index
        ["0"], ["a"], ["0"], ["t"],     # Right index
        ["0"], ["l"], ["n"], ["j"],     # Right middle
        ["0"], ["y"], ["s"], [";"],     # Right ring
        ["0"],  ["0"], ["0"],["0"] ]     # Right pinky
      
      # Thumb row (row 4)
      - [["v"], ["m"], ["k"], ["c"],            # Left thumb cluster
        ["p"], ["f"], ["h"], ["d"]]            # Right thumb cluster
      - [["0"], ["g"], ["w"], ["z"],            # Left thumb cluster 2
        ["x"], ["b"], ["0"], ["q"]]            # Right thumb cluster 2

  fixed_keys:
    # Main key rows (rows 1-3)
    - [true, true, true, true,     # Left pinky
       true, false, false, false,     # Left ring
       true, false, false, false,     # Left middle
       true, true, false, false,     # Left index
       true, false, true, false,     # Right index
       true, false, false, false,     # Right middle
       true, false, false, false,     # Right ring
       true, true, true, true]     # Right pinky
    
    # Thumb row (row 4)
    - [false, false, false, false,                # Left thumb cluster
       false, false, false, false]                # Right thumb cluster
    - [true, false, false, false,                # Left thumb cluster 2
       false, false, true, false]                # Right thumb cluster 2

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: []

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 1

  # modifier types can be "hold", "one_shot", and "long_press"
  #
  # "hold" and "one_shot" modifiers require a field "value" holding a list of
  # either matrix positions or symbols acting as modifiers
  modifiers:
    - Left:
        type: hold
        value: []
      Right:
        type: hold
        value: []
